--- #Install Java OpenJDK 1.8.0

- name: install epel-release
  yum: name=epel-release state=present

- name: install Java
  yum: name={{ java_pkg }} state=present

- name: check javaVersion
  shell: java -version
  register: javaVersion

- name: set two environment variables JAVA_HOME and JRE_HOME
  command: " {{ item }} "
  with_items:
    - cp /etc/profile /etc/profile_backup
    - echo 'export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk' | tee -a /etc/profile
    - echo 'export JRE_HOME=/usr/lib/jvm/jre' | tee -a /etc/profile
    - source /etc/profile
  ignore_errors: yes
- debug: var=javaVersion
  #shell: |
  #  cp /etc/profile /etc/profile_backup
  #  echo 'export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk' | tee -a /etc/profile
  #  echo 'export JRE_HOME=/usr/lib/jvm/jre' | tee -a /etc/profile
  #  source /etc/profile
