---
- name: Install epel-release
  yum: 
    name: epel-release
    state: present
- name: Ensure dependencies are installed.
  package:
    name:
      - libselinux-python
      - libsemanage-python
      - vim
      - git
      - htop
    state: installed

- name: Ensure Jenkins repo is installed.
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
  when: jenkins_repo_url != ''
- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"
- name: Install java 
  yum:
    name: java-1.8.0-openjdk
    state: present
- name: export var
  shell: "echo export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre >> /etc/environment"
- name: Install Jenkins
  yum:
    name: jenkins
    state: latest
- name: Enable Jenkins
  systemd: 
    name: jenkins
    state: started
    enabled: yes
  notify: restart jenkins
